# NumPy Assignment
Create a 1D NumPy array with integers from 1 to 20 and perform various operations.

In [2]:
# Create 1D array with integers from 1 to 20
array_1d = np.arange(1, 21)
print("1D Array:")
print(array_1d)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### Task 1a: Calculate sum, mean, median, and standard deviation

In [3]:
# Calculate statistics
array_sum = np.sum(array_1d)
array_mean = np.mean(array_1d)
array_median = np.median(array_1d)
array_std = np.std(array_1d)

print("\nStatistical Measures:")
print(f"Sum: {array_sum}")
print(f"Mean: {array_mean}")
print(f"Median: {array_median}")
print(f"Standard Deviation: {array_std:.4f}")


Statistical Measures:
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.7663


### Task 1b: Find indices of elements greater than 10

In [4]:
# Find indices where elements are greater than 10
indices_gt_10 = np.where(array_1d > 10)[0]

print("\nIndices of elements greater than 10:")
print(indices_gt_10)
print(f"\nElements at those indices: {array_1d[indices_gt_10]}")


Indices of elements greater than 10:
[10 11 12 13 14 15 16 17 18 19]

Elements at those indices: [11 12 13 14 15 16 17 18 19 20]


---
## Task 2: 2D Array Operations

Create a 2D NumPy array of shape 4×4 with numbers from 1 to 16.

In [5]:
# Create 4x4 2D array with numbers 1 to 16
array_2d = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 Array:")
print(array_2d)

Original 4x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Task 2b: Find the transpose of the array

In [6]:
# Transpose of the array
array_transpose = np.transpose(array_2d)
# Alternative: array_transpose = array_2d.T

print("\nTranspose of the array:")
print(array_transpose)


Transpose of the array:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


### Task 2c: Calculate row-wise and column-wise sums

In [7]:
# Row-wise sum (sum across columns, axis=1)
row_sums = np.sum(array_2d, axis=1)

# Column-wise sum (sum across rows, axis=0)
col_sums = np.sum(array_2d, axis=0)

print("\nRow-wise sums:")
print(row_sums)

print("\nColumn-wise sums:")
print(col_sums)


Row-wise sums:
[10 26 42 58]

Column-wise sums:
[28 32 36 40]


---
## Task 3: Operations on Two 3×3 Arrays

Create two 3×3 arrays filled with random integers between 1 and 20.

In [8]:
# Set random seed for reproducibility (optional)
np.random.seed(42)

# Create two 3x3 arrays with random integers between 1 and 20
array_a = np.random.randint(1, 21, size=(3, 3))
array_b = np.random.randint(1, 21, size=(3, 3))

print("Array A:")
print(array_a)

print("\nArray B:")
print(array_b)

Array A:
[[ 7 20 15]
 [11  8  7]
 [19 11 11]]

Array B:
[[ 4  8  3]
 [ 2 12  6]
 [ 2  1 12]]


### Task 3a: Perform element-wise addition, subtraction, and multiplication

In [9]:
# Element-wise addition
addition = array_a + array_b
print("Element-wise Addition (A + B):")
print(addition)

# Element-wise subtraction
subtraction = array_a - array_b
print("\nElement-wise Subtraction (A - B):")
print(subtraction)

# Element-wise multiplication
multiplication = array_a * array_b
print("\nElement-wise Multiplication (A * B):")
print(multiplication)

Element-wise Addition (A + B):
[[11 28 18]
 [13 20 13]
 [21 12 23]]

Element-wise Subtraction (A - B):
[[ 3 12 12]
 [ 9 -4  1]
 [17 10 -1]]

Element-wise Multiplication (A * B):
[[ 28 160  45]
 [ 22  96  42]
 [ 38  11 132]]


### Task 3b: Compute the dot product of the two arrays

In [10]:
# Dot product (matrix multiplication)
dot_product = np.dot(array_a, array_b)
# Alternative: dot_product = array_a @ array_b

print("Dot Product (A · B):")
print(dot_product)

Dot Product (A · B):
[[ 98 311 321]
 [ 74 191 165]
 [120 295 255]]


---
## Task 4: Reshaping and Slicing

Reshape a 1D array of size 12 into a 3×4 2D array and slice the first two rows and last two columns.

In [11]:
# Create 1D array of size 12
array_12 = np.arange(1, 13)
print("Original 1D array (size 12):")
print(array_12)

# Reshape into 3x4 array
reshaped_array = array_12.reshape(3, 4)
print("\nReshaped to 3x4 array:")
print(reshaped_array)

# Slice: first two rows and last two columns
sliced_array = reshaped_array[:2, -2:]
print("\nSliced array (first 2 rows, last 2 columns):")
print(sliced_array)

Original 1D array (size 12):
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced array (first 2 rows, last 2 columns):
[[3 4]
 [7 8]]
